### ISSUE TITLE
Missing file-as in content.opf

### ISSUE THREAD

**Issue by robinwhittleton** [thewchan/jules-verne_journey-to-the-center-of-the-earth_f-a-malleson_edouard-riou#1]
content.opf: missing “file-as” entries for author / translator / illustrator / artist / transcriber / producer.

**Comment by thewchan** [comment]
Fixed and pushed. Please Check before I close. Thanks!

**Comment by robinwhittleton** [comment]
Ah, sorry, should have made myself clearer. The file-as would present the name in filing order, so `Jules Verne`’s file-as would be `Verne, Jules`. Have a look at some of the other book repos for examples.

**Comment by thewchan** [comment]
Ahhhh now I get it. Okay I tried again. Let me know if it looks right this time. Thanks!

**Comment by robinwhittleton** [comment]
Looks good!
