### ISSUE TITLE
Suggested styling changes for tables

### ISSUE THREAD

**Issue by robinwhittleton** [thewchan/jules-verne_journey-to-the-center-of-the-earth_f-a-malleson_edouard-riou#3]
We should add some margin top and bottom. Maybe change the styling to `table { margin: 1em auto; }`. 

We should also change the `td` padding to em, not px. Typically we’d use 0.5em or 1em.

**Comment by thewchan** [comment]
Fixed and pushed. Please check before I close. Thanks!

**Comment by robinwhittleton** [comment]
Looks good!
