### ISSUE TITLE
Chapter 3 second table markup layout

### ISSUE THREAD

**Issue by robinwhittleton** [thewchan/jules-verne_journey-to-the-center-of-the-earth_f-a-malleson_edouard-riou#4]
Nit, but can we split the first `tr` onto multiple lines to match the following ones?

**Comment by thewchan** [comment]
Weird... I think that might have been a se clean artifact. Anyway, fixed and push. I'll close this after you give a look. Thanks!

**Comment by robinwhittleton** [comment]
Did you push? It’s still this way in the current master commit: https://github.com/thewchan/jules-verne_journey-to-the-center-of-the-earth_f-a-malleson_edouard-riou/blob/f92257a667d10959474a1bfeddda93b085e9af44/src/epub/text/chapter-3.xhtml#L99

**Comment by thewchan** [comment]
Wow I don't know why it's so difficult for me to make this look right lol. Hopefully this time it's fixed!

**Comment by robinwhittleton** [comment]
Thanks!
