### ISSUE TITLE
Language changes

### ISSUE THREAD

**Issue by robinwhittleton** [thewchan/jules-verne_journey-to-the-center-of-the-earth_f-a-malleson_edouard-riou#5]
- `<i xml:lang="sv">`: these are all Danish phrases (Iceland was under Danish rule at the time of publication). So `xml:lang="da"` I guess, or maybe `xml:lang="da-IS"`.
- aðalkirkja / pingstaœr / hraun / skye / blanda / reykir / sting / mistour / vadmel need `<i xml:lang="is">`. We can remove quotes if wrapped.
- Potentially we could change skye to skyr and not italicise it; if we choose to do that it would be a separate [Editorial] commit.

**Comment by robinwhittleton** [comment]
Or, and `<p>Immanis pecoris custos, immanior ipse` / `<p>In Snæfells Joculis craterem` and missing `xml:lang="la"` attributes.

**Comment by thewchan** [comment]
Fixed and pushed. Please check before I close. Thanks!

**Comment by robinwhittleton** [comment]
The blockquote starting `<p>In Snæfells Joculis craterem` still seems to be missing an `xml:lang`, the rest is good.

**Comment by thewchan** [comment]
Ah missed that one. Should be fixed now! Thanks.

**Comment by robinwhittleton** [comment]
Looks good!
